# Generated by Django 5.1.6 on 2025-03-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the ELD log')),
                ('off_duty_hours', models.FloatField(default=0.0, help_text='Hours spent off duty')),
                ('sleeper_berth_hours', models.FloatField(default=0.0, help_text='Hours spent in sleeper berth')),
                ('driving_hours', models.FloatField(default=0.0, help_text='Hours spent driving')),
                ('on_duty_not_driving_hours', models.FloatField(default=0.0, help_text='Hours spent on duty but not driving')),
                ('locations_visited', models.JSONField(default=dict, help_text='JSON field for route stops and locations visited')),
                ('cycle_hours_used', models.FloatField(default=0.0, help_text='Cumulative hours used in the 70-hour/8-day cycle')),
                ('cycle_hours_remaining', models.FloatField(default=70.0, help_text='Hours remaining in the 70-hour/8-day cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
