# Generated by Django 5.1.6 on 2025-03-01 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text='Current location as string or coordinates', max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup location as string or coordinates', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Dropoff location as string or coordinates', max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Current cycle hours used (in hours)')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Trip start time')),
                ('total_distance', models.FloatField(blank=True, help_text='Total trip distance (in miles)', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Trip status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Stop location as string or coordinates', max_length=255)),
                ('type', models.CharField(choices=[('rest', 'Rest Stop'), ('fuel', 'Fuel Stop'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('break', 'Break')], help_text='Type of stop', max_length=20)),
                ('arrival_time', models.DateTimeField(help_text='Estimated arrival time at the stop')),
                ('duration', models.FloatField(help_text='Duration of the stop (in hours)')),
                ('sequence', models.PositiveIntegerField(help_text='Sequence number of the stop in the trip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
