# Generated by Django 5.1.6 on 2025-03-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='current_cycle_used',
            new_name='current_cycle_hours',
        ),
    ]
